### ISSUE TITLE
Estimated timeline of release?

### ISSUE THREAD

**Issue by vishaal27** [icoz69/StableLLAVA#1]
Thanks for your great work, do you have an estimated timeline in mind for the model and data release?
Also note that the arxiv link in your readme is incorrect i think, I assume you want to link it to this paper: https://arxiv.org/abs/2308.10253v1, and the link on the readme was just a mistake?

**Comment by icoz69** [comment]
hi, thank you very much. it's mistake. 
We are going to release our data and prompts very soon, probably in 1~2 weeks. And we will keep releasing new datasets beyond our arxiv.  These datasets will be in LLAVA format, so they can be trained with the raw training code of LLAVA.

**Comment by Hambaobao** [comment]
Hi, may I ask if the training data you created has been released? And where can I find it?🤥
