### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by vishaal27** [icoz69/StableLLAVA#2]
Thanks for your great work, I had a few other questions about the training strategy and datasets used:
1) For training your model, did you fine-tune from the existing LLaVA-13B checkpoint (linear layer and fine-tuned LLM weights), or did you start training the linear layer from scratch? 
2) Do you do both stage 1 (image-text alignment) and stage 2 (instruction tuning) training?
3) For training do you combine both your dataset and LLaVA datasets? What are the exact number of training samples for the baseline and your model for the results in fig. 6?
4) For the human evaluation, how did you collect feedback? Did you give an image-question-answer pair to the humans and asked them to rate it as correct or incorrect>

**Comment by icoz69** [comment]
hi, thanks for your questions

2, our data are only used in stage 1
1, we finetune from the LLAVA-13B that only finishes the first stage
3, we combine both.
4, we provide the reference answers, in the form of many keywords, and ask them to rate it as correct and incorrect

**Comment by vishaal27** [comment]
Great, thanks so much for the prompt response. One other question: do you also do instruction tuning on your model on the LLaVA instruction tuning dataset only? i.e. for instruction tuning you don't use the synthetic data right?

**Comment by icoz69** [comment]
you're right. for the second stage, we only use the raw llava dataset.
